### ISSUE TITLE
Question: Status of IAM Roles For Service Accounts (IRSA)

### ISSUE THREAD

**Issue by groodt** [kubernetes-sigs/aws-ebs-csi-driver#821]
It isn't very clear whether this driver currently supports IAM Roles For Service Accounts (IRSA).

In the AWS docs, it seems that it does: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

However, the docs and a few issues in this repo seem to indicate there are some problems or caveats with this approach?
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474

I would love some clarification on the matter. The [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) seems to be more explicit about IRSA support.

/triage support

**Comment by groodt** [comment]
@vdhanan @wongma7 Apologies for the ping. I'm not sure of the correct protocol to correctly triage this issue.

**Comment by niemeyer** [comment]
Indeed following the official instructions in an attempt to get an EKS with EBS working properly fails after a long sequence of documented manual steps.

**Comment by mikestef9** [comment]
We have official instructions for using IRSA with the EBS CSI driver

https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

Could anyone post more specifics about issues they are encountering?

**Comment by niemeyer** [comment]
I believe the issue I have is the one being fixed by the recently merged but still unreleased #855. The symptom is ebs-plugin failing unless the metadata is exposed, instead of using the service account for doing its job in all cases.

**Comment by groodt** [comment]
Yes, I can confirm that with version v0.10.0 it doesn't work without patching it through to the `hostNetwork`.

I'm going to try version `1.0.0` and will report back.

**Comment by groodt** [comment]
I've run this `kubectl kustomize "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/ecr?ref=v1.0.0" > aws-ebs-csi-driver.yaml`

and it appears that the DaemonSet still requires `hostNetwork`. Should this still be required, even if IRSA should now be possible?

**Comment by groodt** [comment]
Pretty sure this is still failing with `v1.0.0` @mikestef9 @niemeyer 

Here is the error I'm seeing:

```
I0510 09:53:44.807764       1 driver.go:72] Driver: ebs.csi.aws.com Version: v1.0.0
I0510 09:53:44.807898       1 node.go:85] [Debug] Retrieving node info from metadata service
W0510 09:53:48.072144       1 metadata.go:98] EC2 instance metadata is not available
panic: error getting information from metadata service or node object: instance metadata is unavailable and CSI_NODE_NAME env var not set

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc0000c80f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:88 +0x24c
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0xc0001f3f40, 0x7, 0x7, 0xc0006b00c0, 0xc00069c600, 0x1fdec8f)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:97 +0x332
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x212
```

I've got my `AWS_REGION` set in the environment of the container.

**Comment by niemeyer** [comment]
I haven't tried it yet, but did you update all of your deployment from v1.0.0 or just cherry picked the new image?

I see 0b61573a4 added CSI_NODE_NAME to the `ebs-plugin` container in `node.yaml` a few days ago.

**Comment by groodt** [comment]
I generated my YAML as follows:
`kubectl kustomize "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/ecr?ref=v1.0.0" > aws-ebs-csi-driver.yaml`

`CSI_NODE_NAME` seems to only be included in the DaemonSet, not the Deployment.

**Comment by rkennedy-tpl** [comment]
I deployed ebs-csi and after a few errors and some troubleshooting, my initial diagnosis was "it seems to **NOT** be using the ServiceAccount identity and instead falling thru to the EC2 Node IAM account via Instance Metadata Service".

I had to revert [this commit](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/5fc28426c283d00f589cbcff968dbed13e78b268) on the Chart before being able to upgrade to `latest` version of the chart and run on AWS+EKS 1.17. behavior persists.

a good half or more of [the official documentation here](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) is about ServiceAccount and OIDC setup, which is extra annoying if it's falling-thru to EC2 Node IAM metadata service...

I'm about to throw the Policy on the EC2 Node role and see if the errors go away but I'd really rather use Pod-level OIDC Service Accounts and keep the EKS EC2 Node roles minimal.

**Comment by rkennedy-tpl** [comment]
> would be a bit curious if v1 was tagged without this being tested or fixed, though.

I would evaluate it as "irritating, but not surprising". software is produced by humans; software organizations are often large and cluttered, especially ones as large as AWS.

alternatively, "it's open source", and **we** are expected to be the testers 😒

similarly, AWS seems to currently support k8s versions 1.16 - 1.19, so it's a little irritating that I needed to revert a commit to run on 1.17, a supported version that should have all the features required to run ebs-csi-driver.

**Comment by niemeyer** [comment]
@groodt @rkennedy-tpl I suggest reporting your findings related to the service account issues under #474, which was just closed with the intended fixing of that issue. Hopefully it was something minor left out.

On the bright side, it looks like the intention is for this to become an add-on in the console next to CNI, so the development team will be forced to iron out such issues upfront if they expect to have clusters upgrading smoothly.

**Comment by wongma7** [comment]
> CSI_NODE_NAME seems to only be included in the DaemonSet, not the Deployment.

Yes, this is a bug. cc @vdhanan let's add it and test it. I've reopened https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474 until we can confirm it's fixed in a clean helm install + EKS + IAM for SA + instance metadata disabled. Potentially we are doing something wrong in how we set up SDK too, causing it to try to retrieve creds from instance metadata even with env variables set. I don't know, that's why we'll need to test.

Automated test would really help here. To give confidence to both maintainers and users. But this repo is lacking automated testing of EKS. I'm working on it (no ETA). e.g.:
- EKS + IAM instance profile for creds (WIP #852)
- EKS + IAM for SA for creds
- EKS + IAM for SA for creds + instance metadata disabled

I can't directly address all other points/speculation made in the discussion so far. I don't want to get in trouble. I'll acknowledge that I've read it all though.

**Comment by wongma7** [comment]
/cc @AndyXiangLi 
I think I am on the hook for verifying the instance metadata fix on EKS + IAM for SA, let me take that part but appreciate assistance with any other stuff mentioned above.

**Comment by niemeyer** [comment]
> Potentially we are doing something wrong in how we set up SDK too, causing it to try to retrieve creds from instance metadata even with env variables set. I don't know, that's why we'll need to test.

The security best practices documentation for EKS recommends for good reasons to not make metadata available to the pods. Sounds like it would be worth introducing tests for that scenario indeed, as otherwise it's not a very realistic recommendation. And this isn't just about EBS.. if one pod needs access to metadata the launch template needs to have metadata hops set to >=2, which opens it up to all the remaining pods. 

> Automated test would really help here. To give confidence to both maintainers and users.

Indeed, but to be fair even a proper manual test for the scenario described in #474 and recommended as a best practice would have caught it. That said, at least this isn't breaking anyone yet as this never worked properly. The automated tests will be important for it to remain working from now on.

**Comment by niemeyer** [comment]
@wongma7 Thanks for the transparency. Even if the outcome wasn't ideal, the honesty here gives a feeling we can expect a better situation soon.

**Comment by rkennedy-tpl** [comment]
kinda frustrating that when I dig into why specifically Fargate + EBS-CSI is unsupported, it brings me right back to here and to a number of other issues, at least one of which was acknowledged over a year ago.

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/492#issuecomment-623584627

**Comment by groodt** [comment]
Any progress or updates on this @wongma7

**Comment by vdhanan** [comment]
the lingering instance metadata issues should be resolved in v1.1.0 (just released)

**Comment by wongma7** [comment]
the test with instance metadata disabled and controller using IAM for SA (configured via eksctl) is getting reviewed https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/907

**Comment by groodt** [comment]
I've tried to deploy v1.1.0 on my cluster. The rollout worked and everything seemed healthy, but it fails to provision PVC.

Here is the error:
```
Events:
  Type     Reason                Age                From                                                                                      Message
  ----     ------                ----               ----                                                                                      -------
  Normal   WaitForFirstConsumer  69s (x3 over 93s)  persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal   Provisioning          18s (x6 over 66s)  ebs.csi.aws.com_ebs-csi-controller-5c5cf8b9dc-spbpq_0e8cb576-f5ab-4bd7-90bb-8c82d19f4fe1  External provisioner is provisioning volume for claim "app/recommendation-element-tt26g-artifact-storage"
  Warning  ProvisioningFailed    15s (x6 over 62s)  ebs.csi.aws.com_ebs-csi-controller-5c5cf8b9dc-spbpq_0e8cb576-f5ab-4bd7-90bb-8c82d19f4fe1  failed to provision volume with StorageClass "ebs-csi-gp2": rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
  status code: 401, request id:
caused by:
  Normal  ExternalProvisioning  9s (x5 over 66s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

**Comment by wongma7** [comment]
@groodt it looks like the controller is going down the creds chain, can you share the yaml spec of the csi controller pod like ` kubectl get po -o yaml bs-csi-controller-5c5cf8b9dc-spbpq`? Are the AWS_ environment variables there? IAM roles for SA should have injected environment variables onto the pod containing AWS creds, and then the controller should have found those creds.

For reference, in the test, I am using eksctl to configure IAM roles for SA, my eksctl cluster spec has an iam block like this: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/hack/eksctl-patch.yaml#L1 https://eksctl.io/usage/schema/#iam

**Comment by groodt** [comment]
Thanks! You helped me realise that I patched the IRSA annotation to `ebs-csi-node-sa` and not `ebs-csi-controller-sa`.

I've redeployed and now I see the variables injected into the environment.
```
    - name: AWS_ROLE_ARN
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
```

I'll confirm for sure that everything is working after I do a few checks.

Follow-up question: 
Is it expected that the `ebs-csi-node` still has access to hostNetwork and is not using IRSA? Is that also being switched to IRSA at some point?

**Comment by wongma7** [comment]
@groodt nice! 

> Is it expected that the ebs-csi-node still has access to hostNetwork and is not using IRSA? Is that also being switched to IRSA at some point?

ebs-csi-node will not need hostNetwork anymore as of helm chart 1.2.3 + driver version 1.1.0, neither will it need IRSA. This scenario has been exercised by the new test.

The reason that ebs-csi-controller needs IRSA if you have instance metadata disabled is because it needs credentials in order to make AWS API calls, and those credentials need to come from somewhere, so basically if you have instance metadata disabled you must supply it with an alternative source of credentials like IRSA. (Yet another alternative to IRSA would be to generate long-lived credentials and fill in those AWS_ environment variables yourself, but this is not recommended).

ebs-csi-node on the other hand doesn't need to make AWS API calls and so doesn't need credentials.

This is probably best summed up & illustrated with a table.

| | ebs-csi-node | ebs-csi-controller |
|-|-|-|
| Methods for retrieving instance info | Instance metadata if available -> Kubernetes API | Instance metadata if available -> Kubernetes API |
| Methods for retrieving AWS credentials | NOT necessary | IRSA/AWS_ environment variables -> Instance metadata if available |

Thanks for your patience with getting this working, we still have some work to do to improve the docs so I'm going to leave the issue open.

**Comment by groodt** [comment]
Thanks very much @wongma7 That table clears up a lot for me.

> I'll confirm for sure that everything is working after I do a few checks.

I can now confirm that EBS volumes are binding successfully in my environments with v1.1.0 and IRSA.

I'll confirm how things work by removing `hostNetwork` for `ebs-csi-node`.

Final question I think. I imagine that this low-level driver will continue to require a privileged securityContext?
```
        securityContext:
          privileged: true
```

We've been doing security audits of the cluster and trying to reduce IMDS and access to the host as far as possible for all workloads. Would be ideal if AWS could document and push security best-practice further. Many of the AWS provided add-ons don't always come with best-practice configurations by default. It does seem to be improving, and hopefully all the CSI drivers can at least get unplugged from the hostNetwork.

**Comment by wongma7** [comment]
Yes, ebs-csi-node needs to be privileged to perform `mount`. If I recall, CAP_SYS_ADMIN is not sufficient for doing `mount`. Despite https://man7.org/linux/man-pages/man7/capabilities.7.html saying that CAP_SYS_ADMIN lets you do `mount`, it didn't work when last I tried, I needed to be privileged, however that was not recently.

 It's privileged also because it needs read/write access to paths on the host. Because while it could get read/write access to host paths without being privileged, that would require additional set up of the paths' UNIX permissions...being privileged lets us guarantee it will always be able to access those paths. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L100

**Comment by groodt** [comment]
> I'll confirm how things work by removing `hostNetwork` for `ebs-csi-node`.

I've tried to remove `hostNetwork` from the  `ebs-csi-node` DaemonSet and it doesn't appear to work.

```
❯ kubectl -n kube-system logs ebs-csi-node-qxf86 -c ebs-plugin
W0620 22:36:55.260688       1 metadata.go:101] EC2 instance metadata is not available
panic: error getting information from metadata service or node object: nodes "ip-10-0-79-38.ec2.internal" is forbidden: User "system:serviceaccount:kube-system:ebs-csi-node-sa" cannot get resource "nodes" in API group "" at the cluster scope

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc00003a9b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:88 +0x24c
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0xc000157f40, 0x7, 0x7, 0xc0003fda40, 0xc0004415c0, 0x1fded28)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:94 +0x425
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x212
```

**Comment by groodt** [comment]
I've tried to deploy v1.2.0 on my cluster and it fails with the same error above.

```
W0810 02:21:48.667161       1 metadata.go:101] EC2 instance metadata is not available
panic: error getting information from metadata service or node object: nodes "ip-10-0-97-77.ec2.internal" is forbidden: User "system:serviceaccount:kube-system:ebs-csi-node-sa" cannot get resource "nodes" in API group "" at the cluster scope

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc000224ff0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:88 +0x24c
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0xc00050ff40, 0x7, 0x7, 0xc0000379e0, 0xc0000cf560, 0x1fded28)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:94 +0x425
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x212
```

Any thoughts @wongma7

**Comment by groodt** [comment]
I think there might be a `ClusterRoleBinding` missing for ebs-csi-node-sa

**Comment by CarlosRDomin** [comment]
Indeed, that was our problem too, as @groodt points out: the [base folder](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/deploy/kubernetes/base) contains a `clusterrole-csi-node.yaml` and `clusterrolebinding-csi-node.yaml`, but they're not included in the `kustomization.yaml` for some reason. Once manually deployed our error went away :)

**Comment by groodt** [comment]
I've raised this https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1021 to hopefully address this problem.

**Comment by groodt** [comment]
I am happy to confirm that the YAML in the latest [v1.3.0](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/v1.3.0) release works successfully with IRSA and without `hostNetwork` access.

You can inspect the YAML via:
`kubectl kustomize "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/ecr?ref=v1.3.0" > aws-ebs-csi-driver.yaml`

I hope there are tests in place to prevent regressions. I'm happy to mark this issue resolved.

**Comment by wongma7** [comment]
we have end-to-end tests for helm installations but not kustomize. The kustomize templates must be valid because they are generated from the helm equivalents but it is not enough for them to valid if they don't even get applied due to omission from kustomization.yaml

I think a separate issue should track this missing test. A new end-to-end test suite that executes the whole gamut of tests except with a kustomize installed driver instead of a helm installed one is excessive IMO. But a specific test for checking that: 
a) has `make generate-kustomize` been run (to ensure the kustomize templates have parity with the helm chart) and b) does the kustomization.yaml contain all the yamls in the directory (regression test for this case)
is reasonable.

**Comment by groodt** [comment]
I'm going to close this Issue now. For anybody who finds this issue via search, it was resolved in v1.3.0 and you can see my comments here:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/821#issuecomment-923413504

If you'd like to create a new issue to track an end-to-end test if you have not already @wongma7

**Comment by sumanthkumarc** [comment]
I have tried helm and kustomize and used the above https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/821#issuecomment-923413504 too and it still didnt work. I have raised query in community slack at https://kubernetes.slack.com/archives/C8SH2GSL9/p1647490574494619


The combinations i have tried - 

```
Helm 1.5.1 + IRSA
Helm 1.5.1 + Instance profiles
Kustomize  1.3.0 + IRSA
Kustomize 1.3.0 + Instance profiles
```

**Comment by Snehil03** [comment]
Hi,

I am having issues with it since 2 weeks , my ebs-controller logs gives error
```
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I did went again and check more details and found out that there is no aws-secret created as part of driver deployments via eks add-ons.
Could you please provide pointers toward solution ?
